require File.expand_path(File.join(File.dirname(__FILE__), '..', 'spec_helper'))

describe TokenRequestsController do
  describe 'routing' do
    describe '/tokens/:token_id/token_requests' do
      it 'maps POST to the create action' do
        {:post => '/tokens/1/token_requests'}.should \
          route_to(:controller => 'token_requests', :action => 'create',
                   :token_id => '1')
      end

      it 'is generated by token_requests_path' do
        token_requests_path(1).should == '/tokens/1/token_requests'
      end
    end
  end
end
