require File.expand_path(File.join(File.dirname(__FILE__), '..', 'spec_helper'))

describe TokenRequestsController do
  include Devise::TestHelpers

  describe 'routing' do
    describe '/tokens/:token_id/token_requests' do
      it 'maps POST to the create action' do
        {:post => '/tokens/1/token_requests'}.should \
          route_to(:controller => 'token_requests', :action => 'create',
                   :token_id => '1')
      end
    
      it 'is generated by token_requests_path' do
        token_requests_path(1).should == '/tokens/1/token_requests'
      end
    end

    describe '/tokens/:token_id/token_requests/:id/move' do
      it 'maps PUT to the move action' do
        {:put => '/tokens/1/token_requests/2/move'}.should \
          route_to(:controller => 'token_requests', :action => 'move',
                   :token_id => '1', :id => '2')
      end
      
      it 'is generated by move_token_request_path' do
        move_token_request_path(1, 2).should == '/tokens/1/token_requests/2/move'
      end
    end
  end

  shared_examples_for 'it has an index at another controller' do
    it 'and redirect to the token page' do
      get :index, :token_id => '1'
      response.should redirect_to(token_path('1'))
    end
  end

  context '(with anonymous user)' do
    it_should_behave_like 'it has an index at another controller'

    describe '#create' do
      it 'requires an authenticated user' do
        post :create, :token_id => '1'
        response.should redirect_to(new_user_session_path)
      end
    end

    describe '#destroy' do
      it 'requires an authenticated user' do
        delete :destroy, :token_id => '1', :id => '2'
        response.should redirect_to(new_user_session_path)
      end
    end
  end

  context '(with authenticated user)' do
    before(:each) do
      @user = mock_model('User')
      request.env['warden'] = stub('Warden', :authenticate => @user, :authenticate! => @user)
    end

    it_should_behave_like 'it has an index at another controller'

    describe '#create' do
      context 'with invalid data' do
        before(:each) do
          Token.stub!(:find_by_slug!)
          @token_request = mock_model('TokenRequest').as_new_record
          exception = ActiveRecord::RecordInvalid.new(@token_request)
          TokenRequest.stub!(:create!).and_raise(exception)
        end

        it 'renders the tokens/show template' do
          post :create, :token_id => '1'
          response.should render_template('tokens/show')
        end

        it 'assigns the specified token to the template' do
          Token.should_receive(:find_by_slug!).with('1').and_return(:the_token)
          post :create, :token_id => '1'
          assigns(:token).should == :the_token
        end

        it 'assigns the invalid token request to the template' do
          post :create, :token_id => '1'
          assigns(:new_token_request).should === @token_request
        end
      end

      context 'with valid data' do
        it 'should create a new TokenRequest associated with the specified token and current user' do
          Token.should_receive(:find_by_slug!).with('1').and_return(:the_token)
          TokenRequest.should_receive(:create!) \
            .with("purpose" => 'Foo', "urgent" => '1', "token" => :the_token,
                  "user" => @user)
          post :create, :token_id => '1',
            :token_request => {:purpose => 'Foo', :urgent => '1'}
        end

        it 'should redirect to the token page' do
          Token.stub!(:find_by_slug!)
          TokenRequest.stub!(:create!)
          post :create, :token_id => '1'
          response.should redirect_to token_path('1')
        end
      end
    end

    describe '#destroy' do
      it 'destroys the specified TokenRequest' do
        TokenRequest.should_receive(:destroy).with('1')
        delete :destroy, :token_id => 'foo', :id => '1'
      end

      it 'redirects to the token page' do
        TokenRequest.stub!(:destroy)
        delete :destroy, :token_id => 'foo', :id => '1'
        response.should redirect_to(token_path('foo'))
      end
    end
    
    describe '#move' do
      let(:token_request) { stub('TokenRequest', :move => nil) }

      before(:each) do
        TokenRequest.stub!(:find => token_request)
      end
      
      it 'redirects to the token page' do
        put :move, :token_id => 'foo', :id => '1'
        response.should redirect_to(token_path('foo'))
      end
      
      it 'tells the token which way to move' do
        token_request.should_receive(:move).with('movement_direction')
        put :move, :token_id => '1', :id => '2', :where => 'movement_direction'
      end
    end
  end
end
